# See the "GitHub Integration" section of the sonarqube-compose repo's
# README.md for how this project is wired up to a SonarQube server:
# https://github.com/rmrighes-sonar/sonarqube-compose#github-integration
sonar.projectKey=sonarqube-exporter
sonar.projectName=sonarqube-exporter

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.test.inclusions=**/*_test.go
